name: venv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - beautifulsoup4
  - pytorch  # Conda often uses 'pytorch' instead of 'torch'
  - pandas
  - docstring_parser
  - sentencepiece
  - langchain
  - langchain-community
  - langchain-huggingface
  - langsmith
  - langgraph
  - transformers
  - sentence-transformers
  - openai
  - aisuite
  - ragas
  - sacrebleu
  - faiss-gpu
  - python-telegram-bot
  - pip
  - pip:
      - python-dotenv
      - atlassian-python-api
      - ray[all]
      - rouge_score
      - underthesea